### BROWSE
GET http://localhost:8080/api/theme/browse
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MjAxNjIyOTYsImV4cCI6MTcyMDE2NTg5Niwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluQG9wbGF5LmZyIn0.pd3Xu-aKxwXtg0VZi2c7n3CnCF16A2H6hKm5p0IUd80fkhAQDGkjHV2uuckye9DBoaJHqcKqN3puThSL8rfE_93WZlye4tlPekefAuwT9AhXF9mQ-vAwTGO4oVn9RuhAh79jdkw8DQDtnBCTokMtqonXlv4RnFGAbN7F7Y9OR_VlO34tqs4qBLf2RrCTL8Y_JA_XK9WS56sHvLMbptK68N4jzdRSsj4Ez5ifF2a0PE1Im6iZF74y_rHEiNdcCNO0__g1-wNPW-TOKNljiuFsVTkyVxZu3kWw2MOrVXqgmx5zZ4aiDu6QDUzAMUFdGUcDEq-vvgQjKZ-SHrVDFop3iw

### SHOW{id}
GET http://localhost:8080/api/theme/1/show
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MjAxMjU4NjEsImV4cCI6MTcyMDEyOTQ2MSwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluQG9wbGF5LmZyIn0.ox_mQx5ccUY1er8OfPlGj_pBIDj-0VIJnytXdjWsS5H-Co43BlLEz1Rnp3V_VZY_VnE5ltaXF2jKo25gL61__ldStmMji-Z8-9Lz1OpYEiFRL1e94rsgqp3ZrN5wPY7SptQK40SiaU8gkZ25bwb_Z_jt1gxLsBMzqtk7JBxbbX3mVDFAb_z2ilw0KOBRJ3u6Xix2eHaLwbH_9F1GToOHvIgO2wgAeijy_M0hk6fbVvtWeix3eHp7qlef_eTI4fakhin5z7bPa1WIEjEw5muEcb1Fgu5r_Hf5WUNVKoMTkOa-hGKNfpfAXhMlb1L_uJI0TOmkfFgQ8Cz_XGpUOgZiSA