### Add to CART
POST http://localhost:8080/api/order/add
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MjEwNzA5NTMsImV4cCI6MTcyMTA3NDU1Mywicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluQG9wbGF5LmZyIn0.pOeOiS3acX7hTb4_wSOg2zdrz74HlE-B1EC-WOnaiU86jh3vMUKNwRQFquToj8Gas0CFl_faLySygM8aHqReJxOsVXS1fFq_-yJ1xdqd-C5sG1_FluwOpiJwWQ7OsXuc7jY2lwq6gzQewRhN6YVsqg-gmYlnvwd6OUvm3zpgrgrfG-2_Z6R_odSPP08elUlkhRIFY0rT4Qi369t6I10NDpxP3rTDU2qGDu3d8g1FQ91lwGqm0WSVX5-Iydlqd81IRptCt1iw0cmLMyt9Gr5CAHC5l-dbTu6nUovhKv_SxJEyMMt4pMboJbEHMXjinCeExMkPMYr4WlJZHxwJOrvcHw

{
    "game_id": 50
}


### Remove from CART
POST http://localhost:8080/api/order/remove
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MjEwNzA5NTMsImV4cCI6MTcyMTA3NDU1Mywicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluQG9wbGF5LmZyIn0.pOeOiS3acX7hTb4_wSOg2zdrz74HlE-B1EC-WOnaiU86jh3vMUKNwRQFquToj8Gas0CFl_faLySygM8aHqReJxOsVXS1fFq_-yJ1xdqd-C5sG1_FluwOpiJwWQ7OsXuc7jY2lwq6gzQewRhN6YVsqg-gmYlnvwd6OUvm3zpgrgrfG-2_Z6R_odSPP08elUlkhRIFY0rT4Qi369t6I10NDpxP3rTDU2qGDu3d8g1FQ91lwGqm0WSVX5-Iydlqd81IRptCt1iw0cmLMyt9Gr5CAHC5l-dbTu6nUovhKv_SxJEyMMt4pMboJbEHMXjinCeExMkPMYr4WlJZHxwJOrvcHw

{
    "game_id": 50,
    "quantity": 1
}

### Remove CART
POST http://localhost:8080/api/order/clear
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MjEwNzA5NTMsImV4cCI6MTcyMTA3NDU1Mywicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluQG9wbGF5LmZyIn0.pOeOiS3acX7hTb4_wSOg2zdrz74HlE-B1EC-WOnaiU86jh3vMUKNwRQFquToj8Gas0CFl_faLySygM8aHqReJxOsVXS1fFq_-yJ1xdqd-C5sG1_FluwOpiJwWQ7OsXuc7jY2lwq6gzQewRhN6YVsqg-gmYlnvwd6OUvm3zpgrgrfG-2_Z6R_odSPP08elUlkhRIFY0rT4Qi369t6I10NDpxP3rTDU2qGDu3d8g1FQ91lwGqm0WSVX5-Iydlqd81IRptCt1iw0cmLMyt9Gr5CAHC5l-dbTu6nUovhKv_SxJEyMMt4pMboJbEHMXjinCeExMkPMYr4WlJZHxwJOrvcHw

### Checkout
POST http://localhost:8080/api/order/checkout
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MjEwNzA5NTMsImV4cCI6MTcyMTA3NDU1Mywicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluQG9wbGF5LmZyIn0.pOeOiS3acX7hTb4_wSOg2zdrz74HlE-B1EC-WOnaiU86jh3vMUKNwRQFquToj8Gas0CFl_faLySygM8aHqReJxOsVXS1fFq_-yJ1xdqd-C5sG1_FluwOpiJwWQ7OsXuc7jY2lwq6gzQewRhN6YVsqg-gmYlnvwd6OUvm3zpgrgrfG-2_Z6R_odSPP08elUlkhRIFY0rT4Qi369t6I10NDpxP3rTDU2qGDu3d8g1FQ91lwGqm0WSVX5-Iydlqd81IRptCt1iw0cmLMyt9Gr5CAHC5l-dbTu6nUovhKv_SxJEyMMt4pMboJbEHMXjinCeExMkPMYr4WlJZHxwJOrvcHw