### Add to CART
POST http://localhost:8080/api/order/add
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MjEwMzE0MDAsImV4cCI6MTcyMTAzNTAwMCwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluQG9wbGF5LmZyIn0.oF6nFVplJV49p2JbnLzRFu5JTHcvsWTJq2PcypmF7_9OmG6V_7eP0GopICz2HkXxSL40HT-o3XMJ_Df5eJYoCm1wPPenATsRUTVMC5FIWylWXIKA5HFOE87ow4ou81CYndCey8QYGnwnJgh8_n-36In_XI7P3fEURKVsqwKHrURaZ_PK30BQxesgWZHaI38E2HHq9yAM1rPanq2_Qutsj0uO0v1NLWGgYDfaJpTAfqUKCTmG6_qVgB8RVSXBjPH1pSvKLbFIiNJJBnt2zbzAJSjzxk7F2FjkZHTu01r9orrbq2HtZqmoO7gogI7fOAn8Uu-qhLJQiyNXq9xFsin8yg

{
    "game_id": 5
}


### Remove from CART
POST http://localhost:8080/api/order/remove
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MjEwMzE0MDAsImV4cCI6MTcyMTAzNTAwMCwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluQG9wbGF5LmZyIn0.oF6nFVplJV49p2JbnLzRFu5JTHcvsWTJq2PcypmF7_9OmG6V_7eP0GopICz2HkXxSL40HT-o3XMJ_Df5eJYoCm1wPPenATsRUTVMC5FIWylWXIKA5HFOE87ow4ou81CYndCey8QYGnwnJgh8_n-36In_XI7P3fEURKVsqwKHrURaZ_PK30BQxesgWZHaI38E2HHq9yAM1rPanq2_Qutsj0uO0v1NLWGgYDfaJpTAfqUKCTmG6_qVgB8RVSXBjPH1pSvKLbFIiNJJBnt2zbzAJSjzxk7F2FjkZHTu01r9orrbq2HtZqmoO7gogI7fOAn8Uu-qhLJQiyNXq9xFsin8yg

{
    "game_id": 5,
    "quantity": 1
}

### Remove CART
POST http://localhost:8080/api/order/clear
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MjEwMzE0MDAsImV4cCI6MTcyMTAzNTAwMCwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluQG9wbGF5LmZyIn0.oF6nFVplJV49p2JbnLzRFu5JTHcvsWTJq2PcypmF7_9OmG6V_7eP0GopICz2HkXxSL40HT-o3XMJ_Df5eJYoCm1wPPenATsRUTVMC5FIWylWXIKA5HFOE87ow4ou81CYndCey8QYGnwnJgh8_n-36In_XI7P3fEURKVsqwKHrURaZ_PK30BQxesgWZHaI38E2HHq9yAM1rPanq2_Qutsj0uO0v1NLWGgYDfaJpTAfqUKCTmG6_qVgB8RVSXBjPH1pSvKLbFIiNJJBnt2zbzAJSjzxk7F2FjkZHTu01r9orrbq2HtZqmoO7gogI7fOAn8Uu-qhLJQiyNXq9xFsin8yg

### Checkout
POST http://localhost:8080/api/order/checkout
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MjEwMzE0MDAsImV4cCI6MTcyMTAzNTAwMCwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluQG9wbGF5LmZyIn0.oF6nFVplJV49p2JbnLzRFu5JTHcvsWTJq2PcypmF7_9OmG6V_7eP0GopICz2HkXxSL40HT-o3XMJ_Df5eJYoCm1wPPenATsRUTVMC5FIWylWXIKA5HFOE87ow4ou81CYndCey8QYGnwnJgh8_n-36In_XI7P3fEURKVsqwKHrURaZ_PK30BQxesgWZHaI38E2HHq9yAM1rPanq2_Qutsj0uO0v1NLWGgYDfaJpTAfqUKCTmG6_qVgB8RVSXBjPH1pSvKLbFIiNJJBnt2zbzAJSjzxk7F2FjkZHTu01r9orrbq2HtZqmoO7gogI7fOAn8Uu-qhLJQiyNXq9xFsin8yg