### BROWSE
GET http://localhost:8080/api/game/browse
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MjAxMDI2NjgsImV4cCI6MTcyMDEwNjI2OCwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluQG9wbGF5LmZyIn0.x4Bh7TDYSkbFhX4jVGwNyD-OHlx0t9NlKfl3mmw93Mz7OEge5kSDmNE5d7sNks6B-a5iuGM1zPa9fTMeMigmbgrs88dGg41gQZV-PB_gij1uNthNx8zVrRayAzO0cr3WAtUs2apoXpjR-ZoGObbcs_9-YOk5VEOr6vJKhzI5yb4rt24zl5WC_FfW0fdJOcu1t5lnr6MMdMEziZCjnW7Ir0tLiXZiCblyN2Je1D4G2JAocHUqBOjgEI3BIbeaZ7YwQ7dtl3OaC-mrfMmKU801DlCZtFP9pnbAMek2ZfhTf5UyLq57CVcBb49Lx9VF6y7BumSTSwIWQjHULZLsbKiUew


### SHOW{id}
GET http://localhost:8080/api/game/51/show
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MjAwNzQ5OTEsImV4cCI6MTcyMDA3ODU5MSwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluQG9wbGF5LmZyIn0.XcQ2T-rUL5OImDht72vqIrg2jlAO_sSVAm6t5NEt3T7pFG7-bu4njxLi0TQG7x_VwniH2GMj_kPkqoMfSb0kCw7rPzn8kNnzqyo-sDSF2RtNnKfEXIPsy7VkP-SXESWo5j2FvMSBKT7qtbIqnG0djJbSyFcRaUCE2kxjsKTc2Cm_CFFs5eW3hQ-7-Xq4HXFTf1pnADcyUL5-nWTOX2kO5C5OALB-dLt_LmcYlDZ-iXTD9Yn1Gr1tc60N0hmpXuuRf06BVnio_4preSZS5svJKHniiB6sRfIGfKm4iKrsKdRKZoAPJ49yq6M_mthoE4-_siZlEIjvvf0mWz-8JgLbog