### BROWSE
GET http://localhost:8080/api/game/browse
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MjAxMjk3ODQsImV4cCI6MTcyMDEzMzM4NCwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluQG9wbGF5LmZyIn0.FJbR1b9bmc0CWMbAUgJ8GvIv2Bim_Gj3Lt44ThVr1z-LMQ3hxN3n3YCT3LU86ZoNr4A2fP-d2QInMSeEq6hxq4K0iIjfA1dSKdcxHTPOX5gS70HhoiTFz_Ks3sHu6urm2Kkw57KhkIjWboZS21l6kLkwuA03NxmHdZoXINpN_fd76GNdf9DI3suT4B0RC3-HfZL48459Mh7aXkrWMopdIarHENqO8UWjztzzciGP7u5j09J_mifpXcBRmbCyJ-kdTUgnhpklRpQRaig5L-JZKN2LnFfXnxKYnevyDXHVGezhOeZSUqedUuoAwQwy6i2oKBNPCuqMwpoELkWbO29RYg


### SHOW{id}
GET http://localhost:8080/api/game/1/show
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MjAxMDg4NDQsImV4cCI6MTcyMDExMjQ0NCwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluQG9wbGF5LmZyIn0.jBYWDUUBJvRmeaLLRkmNMjiXhDLY5vKoHMqESskJnn4Y-rk-yp4Nb_IGB2gmK57UihP_51exn3l_pwQcLGDIBZR0yf7wgG4h-FoEmlEj2cX-r4D9S0l3Y19D5Kas_DXGuGtZJFozIAQLMbeH6HKNzxlrB-iMEgw5UIK74L9F95Kr_SBYhU4G0xyIVRhj_8Vuw5p-6WZb6rOqf0_UCh38L4XHOMiMG6vHi2OjUYbOi61esboPTrR7InG9qxrRA9-JkMlJPqStzkiRqxviJNBR-GKq1DKG_XGU0HdF_BxpZhw9xIY73n3XMS9CzU3Yqz5nymmHaYRQ7STaYKujiyIyvg