### BROWSE
GET http://localhost:8081/api/category/browse
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MjAwODU0NDAsImV4cCI6MTcyMDA4OTA0MCwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluQG9wbGF5LmZyIn0.ZWFYLmQEvhXBh_yZt34bi0y5LWioRPfwofvbghRghHIWS59EWWioFCywx9AhqGTLzsHXdjJ6AY1KtvS4Hg-htqr2YeH8eMrAdacsxfg5hKW51XLlMwMWHIV4V_9lrM-egVBWd_SJ3EbMDT4x_vSm_XBZxCo3crcos0q2EaihkWIC_HLmhKuNXOdZoRmD7kigZ7CfKV_3NbQNKrHWvvEosRhtjem9V_QICsZPPGsFBFbCeBDBTTl0us4M8hKWt5YYguoOumFPw8lwzxink-GS-RA-t2bUSyMG4Q5HHBexl5Kfe6A4BQhl2brhykOemCLFi8s5Ula7Ip082LsoFG_aqw


### SHOW{id}
GET http://localhost:8080/api/category/11/show
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MjAwMTM0MjUsImV4cCI6MTcyMDAxNzAyNSwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluQG9wbGF5LmZyIn0.CIq6FhKQMjIbVE3tXZtImgGqteJiE5xCHy78qxqPLR_h_m_i4ea6cCUwTOGy9cqyMnDtPrKlIgXSiKKXUiRsnWoRNeVeNyYLoWC7_Ai8Qn-m8LG8T0aVz2T25EOQuLYzkvHDsH2Gov5e80yf0omHYlEBbgTe0QRhEHeWilhiS8_DnO2dHTrCcr_9LH9MKL0oOj85TJolgA9iF1Kq6ZOIIJctEn600lHxA9T9bMklO6ox-xiJuBu8eircnHJNrTAAAHAfwHwAdme4xio7yUVXSzJadRPewAfTkIUFqlzk7utOyeRTzgB9iBDISt1EFYdta5UGhlAueDIH_8ykA9g5TQ