### BROWSE
GET http://localhost:8080/api/tag/browse
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MjAxMjU4NjEsImV4cCI6MTcyMDEyOTQ2MSwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluQG9wbGF5LmZyIn0.ox_mQx5ccUY1er8OfPlGj_pBIDj-0VIJnytXdjWsS5H-Co43BlLEz1Rnp3V_VZY_VnE5ltaXF2jKo25gL61__ldStmMji-Z8-9Lz1OpYEiFRL1e94rsgqp3ZrN5wPY7SptQK40SiaU8gkZ25bwb_Z_jt1gxLsBMzqtk7JBxbbX3mVDFAb_z2ilw0KOBRJ3u6Xix2eHaLwbH_9F1GToOHvIgO2wgAeijy_M0hk6fbVvtWeix3eHp7qlef_eTI4fakhin5z7bPa1WIEjEw5muEcb1Fgu5r_Hf5WUNVKoMTkOa-hGKNfpfAXhMlb1L_uJI0TOmkfFgQ8Cz_XGpUOgZiSA

### SHOW{id}
GET http://localhost:8080/api/tag/1/show
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MjAxMDg4NDQsImV4cCI6MTcyMDExMjQ0NCwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluQG9wbGF5LmZyIn0.jBYWDUUBJvRmeaLLRkmNMjiXhDLY5vKoHMqESskJnn4Y-rk-yp4Nb_IGB2gmK57UihP_51exn3l_pwQcLGDIBZR0yf7wgG4h-FoEmlEj2cX-r4D9S0l3Y19D5Kas_DXGuGtZJFozIAQLMbeH6HKNzxlrB-iMEgw5UIK74L9F95Kr_SBYhU4G0xyIVRhj_8Vuw5p-6WZb6rOqf0_UCh38L4XHOMiMG6vHi2OjUYbOi61esboPTrR7InG9qxrRA9-JkMlJPqStzkiRqxviJNBR-GKq1DKG_XGU0HdF_BxpZhw9xIY73n3XMS9CzU3Yqz5nymmHaYRQ7STaYKujiyIyvg