### Redirect to backoffice
GET http://localhost:8080/api/redirect
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MjEyODczNjYsImV4cCI6MTcyMTI5MDk2Niwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluQG9wbGF5LmZyIn0.MQShHHq_DGVXZH68x8YD6m4HymGotgvoKr1B-94zMOnkZqvY3t7yWIpWqszQYJ6icLWsBnKwEgdh2_dTfHL-3qYgsHs8ew8-rQgm_tmyiq93nHJ484Dhoq3wsG_wMXKOvLBkHjJUHDdPT2U42WN4_CzwPQZq5L_sTMC9f88twaS6rEFrAzlTfTQIv4nDRwsyfSNtyxSa97D82xjorSGeuTQ_WHFlBWldRU1lbT9OJYUkmjw12aHe_-SubGNx2HbISvlRYg7PhzATd1e9yzYCDreHycCJd2bPufexPJ6x03qzpVRVCO_Z2nOIRkuZFLDChpomPKgvJByv0hfnXoIfUg