### BROWSe
GET http://localhost:8080/api/category/browse
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MjAwOTgyMDYsImV4cCI6MTcyMDEwMTgwNiwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluQG9wbGF5LmZyIn0.J6fo1TXKU5Wsy8KgT0MckJlgWzfbe9t0zbw2IEEQUVyYww8AU7PDGM25WnxbUIcX8w8z1pr8oVYwC2z0-rfLHR0jwzY9H-Q0eqcKC-7p6w-t87Y_qCrsgQHBaDywv3pYQ9DZc3vw8ul3Z5WyB1NMYOYntnwF5rYbtJmI0Q-ceqwB1eprAhmhkmfCy26dtSkq0FANMa7Ux6GMJqppAwjXsRjaDItJvnjwHMUG4x3gxp59xHnMJBGENnAimRwNdISwK__nz17P1CfAoewKbkzwAt3uwGVqNOOrFNtY5qzUnIcwmwSPtU7GScNbm6NKBFmZomLJ7Pn_ZL4enTN1MbauEA


### SHOW{id}
GET http://localhost:8080/api/category/11/show
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MjAwODgyODYsImV4cCI6MTcyMDA5MTg4Niwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluQG9wbGF5LmZyIn0.s7UyjGh9te7vDwUL4-TBE6WE3-djvW-YCgjejx-LKoEx_BkydW5OsYm61iL49cxBlxjYEzXLP3XVySbF1RH9H5Ew6ZcdKSJh5AsB-6DVU19pMtbxP6H9GjiChiarppgu9Xrgu5OHtPsmXVZr0hXVhZ4ElE1mM2alMhaHKbVkrVEMHfkEcy6Y5cXAd7gRQwaHZgXPwZ7lSlAyXjjCMsN01YV5dwGO7rkirF_UiIC7Z40mIcWEmsdljh1Ag01o1ITpQHoRyAYa81FiZl3YflpSsh4vKhr7Wp1t51tkoe7QxZkS88orUeXVQYx_iNBdXNEBIgWnq7eJ47GzFBa4duXC4Q