### Redirect to backoffice
GET http://localhost:8080/api/redirect
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MjEyNDY0MjEsImV4cCI6MTcyMTI1MDAyMSwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluQG9wbGF5LmZyIn0.M8bVJFjuojGae_X_QalXNgFjOHtRVrFaJizdKelWR2Zw9ixUxCD-t6KyQKg-bgkLQ242ctHRB76k3V3YNeCjili8oajIHO7gC4mJT2o6I6CiH3EVeRl7W23s4x0iO6dJgB_Dtl9EPvXNoqKQfhMbUt1vi7412aGSFjl-8apkAYMFtNcoPl3AziLazw-p7MhD87d9Ok22D6IJV2REgjhM8Y9cB8Gk4tZvpukOmkFpXUgIJyE99QfYeCqMyWQ-MV2C4vou3qWPnPX7ry3oeLWyK_HhULe5R5PU9dcRbUR4lVOBhBqC0opRyB1hfohdGe9u8ZCCQGAPXipZM8Bm5T0wkg