### BROWSE
GET http://localhost:8080/api/tag/browse
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MjAwMTM0MjUsImV4cCI6MTcyMDAxNzAyNSwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluQG9wbGF5LmZyIn0.CIq6FhKQMjIbVE3tXZtImgGqteJiE5xCHy78qxqPLR_h_m_i4ea6cCUwTOGy9cqyMnDtPrKlIgXSiKKXUiRsnWoRNeVeNyYLoWC7_Ai8Qn-m8LG8T0aVz2T25EOQuLYzkvHDsH2Gov5e80yf0omHYlEBbgTe0QRhEHeWilhiS8_DnO2dHTrCcr_9LH9MKL0oOj85TJolgA9iF1Kq6ZOIIJctEn600lHxA9T9bMklO6ox-xiJuBu8eircnHJNrTAAAHAfwHwAdme4xio7yUVXSzJadRPewAfTkIUFqlzk7utOyeRTzgB9iBDISt1EFYdta5UGhlAueDIH_8ykA9g5TQ


### SHOW{id}
GET http://localhost:8080/api/tag/22/show
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MjAwMTM0MjUsImV4cCI6MTcyMDAxNzAyNSwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluQG9wbGF5LmZyIn0.CIq6FhKQMjIbVE3tXZtImgGqteJiE5xCHy78qxqPLR_h_m_i4ea6cCUwTOGy9cqyMnDtPrKlIgXSiKKXUiRsnWoRNeVeNyYLoWC7_Ai8Qn-m8LG8T0aVz2T25EOQuLYzkvHDsH2Gov5e80yf0omHYlEBbgTe0QRhEHeWilhiS8_DnO2dHTrCcr_9LH9MKL0oOj85TJolgA9iF1Kq6ZOIIJctEn600lHxA9T9bMklO6ox-xiJuBu8eircnHJNrTAAAHAfwHwAdme4xio7yUVXSzJadRPewAfTkIUFqlzk7utOyeRTzgB9iBDISt1EFYdta5UGhlAueDIH_8ykA9g5TQ