# ### BROWSE
# GET http://localhost:8080/api/user
# Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MjA5OTM4NjUsImV4cCI6MTcyMDk5NzQ2NSwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluQG9wbGF5LmZyIn0.IarOysqpxLp-MtmYHSXa3-6n1z0oMQUHriR9s1K3-50_Ak2klU-7GzfVtLalN9urrm31TK5xtk732ELFaAKxoFiAbdOIYPr5hhtansjUjyJcmYp3sRFBWwzc2pE0cQHqbwOXarTgy275tj2m-dhTiP4Gwa2mu27D2OqAVP7_AauoMA470M7w06OVOJwSQ6NUsmKGkLpeZAfvqr30Lvrbjj3fxtezPuIQrwaQ5F7SkQv-LZFPZiMk29x29-fqWKC7t4F0R03njlMg0GdogYwTSZXamLHh6bqWWylbbA7wyoSAqM7vIJy_jUfXBujOXjknuf169KLew_ZgwCt5DTIKbw


### DETAIL
GET http://localhost:8080/api/user/detail
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MjA5OTM4NjUsImV4cCI6MTcyMDk5NzQ2NSwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluQG9wbGF5LmZyIn0.IarOysqpxLp-MtmYHSXa3-6n1z0oMQUHriR9s1K3-50_Ak2klU-7GzfVtLalN9urrm31TK5xtk732ELFaAKxoFiAbdOIYPr5hhtansjUjyJcmYp3sRFBWwzc2pE0cQHqbwOXarTgy275tj2m-dhTiP4Gwa2mu27D2OqAVP7_AauoMA470M7w06OVOJwSQ6NUsmKGkLpeZAfvqr30Lvrbjj3fxtezPuIQrwaQ5F7SkQv-LZFPZiMk29x29-fqWKC7t4F0R03njlMg0GdogYwTSZXamLHh6bqWWylbbA7wyoSAqM7vIJy_jUfXBujOXjknuf169KLew_ZgwCt5DTIKbw

### Register User
POST http://localhost:8080/api/user/register
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MjEwMzE0MDAsImV4cCI6MTcyMTAzNTAwMCwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluQG9wbGF5LmZyIn0.oF6nFVplJV49p2JbnLzRFu5JTHcvsWTJq2PcypmF7_9OmG6V_7eP0GopICz2HkXxSL40HT-o3XMJ_Df5eJYoCm1wPPenATsRUTVMC5FIWylWXIKA5HFOE87ow4ou81CYndCey8QYGnwnJgh8_n-36In_XI7P3fEURKVsqwKHrURaZ_PK30BQxesgWZHaI38E2HHq9yAM1rPanq2_Qutsj0uO0v1NLWGgYDfaJpTAfqUKCTmG6_qVgB8RVSXBjPH1pSvKLbFIiNJJBnt2zbzAJSjzxk7F2FjkZHTu01r9orrbq2HtZqmoO7gogI7fOAn8Uu-qhLJQiyNXq9xFsin8yg

{
    "firstname": "Gui",
    "lastname": "Gui",
    "nickname": "GIOM",
    "email": "gui.@oplay.fr",
    "password": "123",
    "picture": ""
}

### Edit User
PATCH http://localhost:8080/api/user/edit
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MjEwMzAyMDYsImV4cCI6MTcyMTAzMzgwNiwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluQG9wbGF5LmZyIn0.fV1DwuA4LJVqurewL69PAOnIZnAaNrdu4YQWUOSULr1cH5KtSWGIy_En7ARa5fGDWQ_DQePSJi_MUqMJ3yvLr41AUs8wcROF0Rvdtwpu5kguCiYLChFwWN5YEVLfhwEFlvOJcCkFD4By8TIlaU6mMt36cklskChuD6a1kSa7Rw6fkRzKb-wgy3xp2TgZEexX-1_uGf5XR4jfwG0iyYsGVvDEzSBMh-WY3r0N3hOaDgIHPgj4LzMy7wVYh2zfShedE0hfYT8QmfRes6qSqnpLT1-4ZlGotDIXn1Suquk7Taa0F46tkglLcdEhvkIZFDs4s8qhmA_AVKT0JrYg0HRlzQ

{
    "firstname": "Test2",
    "lastname": "Test2",
    "nickname": "Test2",
    "email": "test2@example.com",
    "password": "password123",
    "picture": ""
}


### Prefered Tag User
POST http://localhost:8080/api/user/tags
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MjA5OTM4NjUsImV4cCI6MTcyMDk5NzQ2NSwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluQG9wbGF5LmZyIn0.IarOysqpxLp-MtmYHSXa3-6n1z0oMQUHriR9s1K3-50_Ak2klU-7GzfVtLalN9urrm31TK5xtk732ELFaAKxoFiAbdOIYPr5hhtansjUjyJcmYp3sRFBWwzc2pE0cQHqbwOXarTgy275tj2m-dhTiP4Gwa2mu27D2OqAVP7_AauoMA470M7w06OVOJwSQ6NUsmKGkLpeZAfvqr30Lvrbjj3fxtezPuIQrwaQ5F7SkQv-LZFPZiMk29x29-fqWKC7t4F0R03njlMg0GdogYwTSZXamLHh6bqWWylbbA7wyoSAqM7vIJy_jUfXBujOXjknuf169KLew_ZgwCt5DTIKbw

{
    "tag_ids": [57, 58, 59]
}

### Selected Category User
POST http://localhost:8080/api/user/categories
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MjA5OTM4NjUsImV4cCI6MTcyMDk5NzQ2NSwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluQG9wbGF5LmZyIn0.IarOysqpxLp-MtmYHSXa3-6n1z0oMQUHriR9s1K3-50_Ak2klU-7GzfVtLalN9urrm31TK5xtk732ELFaAKxoFiAbdOIYPr5hhtansjUjyJcmYp3sRFBWwzc2pE0cQHqbwOXarTgy275tj2m-dhTiP4Gwa2mu27D2OqAVP7_AauoMA470M7w06OVOJwSQ6NUsmKGkLpeZAfvqr30Lvrbjj3fxtezPuIQrwaQ5F7SkQv-LZFPZiMk29x29-fqWKC7t4F0R03njlMg0GdogYwTSZXamLHh6bqWWylbbA7wyoSAqM7vIJy_jUfXBujOXjknuf169KLew_ZgwCt5DTIKbw

{
    "category_ids": [25, 26, 27]
}


### Selected Theme User
POST http://localhost:8080/api/user/theme
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MjA5OTM4NjUsImV4cCI6MTcyMDk5NzQ2NSwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluQG9wbGF5LmZyIn0.IarOysqpxLp-MtmYHSXa3-6n1z0oMQUHriR9s1K3-50_Ak2klU-7GzfVtLalN9urrm31TK5xtk732ELFaAKxoFiAbdOIYPr5hhtansjUjyJcmYp3sRFBWwzc2pE0cQHqbwOXarTgy275tj2m-dhTiP4Gwa2mu27D2OqAVP7_AauoMA470M7w06OVOJwSQ6NUsmKGkLpeZAfvqr30Lvrbjj3fxtezPuIQrwaQ5F7SkQv-LZFPZiMk29x29-fqWKC7t4F0R03njlMg0GdogYwTSZXamLHh6bqWWylbbA7wyoSAqM7vIJy_jUfXBujOXjknuf169KLew_ZgwCt5DTIKbw

{
    "theme_id": 25
}
