### BROWSE
GET http://localhost:8080/api/game
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MjA5OTM4NjUsImV4cCI6MTcyMDk5NzQ2NSwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluQG9wbGF5LmZyIn0.IarOysqpxLp-MtmYHSXa3-6n1z0oMQUHriR9s1K3-50_Ak2klU-7GzfVtLalN9urrm31TK5xtk732ELFaAKxoFiAbdOIYPr5hhtansjUjyJcmYp3sRFBWwzc2pE0cQHqbwOXarTgy275tj2m-dhTiP4Gwa2mu27D2OqAVP7_AauoMA470M7w06OVOJwSQ6NUsmKGkLpeZAfvqr30Lvrbjj3fxtezPuIQrwaQ5F7SkQv-LZFPZiMk29x29-fqWKC7t4F0R03njlMg0GdogYwTSZXamLHh6bqWWylbbA7wyoSAqM7vIJy_jUfXBujOXjknuf169KLew_ZgwCt5DTIKbw


### SHOW{id}
GET http://localhost:8080/api/game/281
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MjA5OTM4NjUsImV4cCI6MTcyMDk5NzQ2NSwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluQG9wbGF5LmZyIn0.IarOysqpxLp-MtmYHSXa3-6n1z0oMQUHriR9s1K3-50_Ak2klU-7GzfVtLalN9urrm31TK5xtk732ELFaAKxoFiAbdOIYPr5hhtansjUjyJcmYp3sRFBWwzc2pE0cQHqbwOXarTgy275tj2m-dhTiP4Gwa2mu27D2OqAVP7_AauoMA470M7w06OVOJwSQ6NUsmKGkLpeZAfvqr30Lvrbjj3fxtezPuIQrwaQ5F7SkQv-LZFPZiMk29x29-fqWKC7t4F0R03njlMg0GdogYwTSZXamLHh6bqWWylbbA7wyoSAqM7vIJy_jUfXBujOXjknuf169KLew_ZgwCt5DTIKbw
