### BROWSE
GET http://localhost:8080/api/tag/browse
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MjAwNzQ5OTEsImV4cCI6MTcyMDA3ODU5MSwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluQG9wbGF5LmZyIn0.XcQ2T-rUL5OImDht72vqIrg2jlAO_sSVAm6t5NEt3T7pFG7-bu4njxLi0TQG7x_VwniH2GMj_kPkqoMfSb0kCw7rPzn8kNnzqyo-sDSF2RtNnKfEXIPsy7VkP-SXESWo5j2FvMSBKT7qtbIqnG0djJbSyFcRaUCE2kxjsKTc2Cm_CFFs5eW3hQ-7-Xq4HXFTf1pnADcyUL5-nWTOX2kO5C5OALB-dLt_LmcYlDZ-iXTD9Yn1Gr1tc60N0hmpXuuRf06BVnio_4preSZS5svJKHniiB6sRfIGfKm4iKrsKdRKZoAPJ49yq6M_mthoE4-_siZlEIjvvf0mWz-8JgLbog

### SHOW{id}
GET http://localhost:8080/api/tag/22/show
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MjAwNzQ5OTEsImV4cCI6MTcyMDA3ODU5MSwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluQG9wbGF5LmZyIn0.XcQ2T-rUL5OImDht72vqIrg2jlAO_sSVAm6t5NEt3T7pFG7-bu4njxLi0TQG7x_VwniH2GMj_kPkqoMfSb0kCw7rPzn8kNnzqyo-sDSF2RtNnKfEXIPsy7VkP-SXESWo5j2FvMSBKT7qtbIqnG0djJbSyFcRaUCE2kxjsKTc2Cm_CFFs5eW3hQ-7-Xq4HXFTf1pnADcyUL5-nWTOX2kO5C5OALB-dLt_LmcYlDZ-iXTD9Yn1Gr1tc60N0hmpXuuRf06BVnio_4preSZS5svJKHniiB6sRfIGfKm4iKrsKdRKZoAPJ49yq6M_mthoE4-_siZlEIjvvf0mWz-8JgLbog