### BROWSE
GET http://localhost:8080/api/category/browse
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MjAwODUyOTIsImV4cCI6MTcyMDA4ODg5Miwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluQG9wbGF5LmZyIn0.Xjm_cZ9iIIQbcG0Z4IBCVaiO5Ps_r0vc5PgN-NC2Qx0GlAyVTlkwpe5SiGfih8Y5DvAAQBaVu34iBTLTQkP1AlwL4TYNG1pAhuIpvBHN92f4BYYA2UV6N4tw5-tuzlX6QPv6PIlU2Q-71nmVnTAdYdufp0_6XjEqYvqJX1E38-Q6jqjSfIfhTPxxDujH6xC61LhyZenCBh-wr--K4vtNFFcLG7gOx50BSjFfMpgfA4SMw4VMeXomog_YULNlVDqd6azuorz1j99wxDe3-P2mAHH0qQiu842KNy2V6WD2oAjiOZDrC_0trlm3qDcUGGrqYsTptUNmewIsaKy8jo9GrQ


### SHOW{id}
GET http://localhost:8080/api/category/11/show
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MjAwMTM0MjUsImV4cCI6MTcyMDAxNzAyNSwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluQG9wbGF5LmZyIn0.CIq6FhKQMjIbVE3tXZtImgGqteJiE5xCHy78qxqPLR_h_m_i4ea6cCUwTOGy9cqyMnDtPrKlIgXSiKKXUiRsnWoRNeVeNyYLoWC7_Ai8Qn-m8LG8T0aVz2T25EOQuLYzkvHDsH2Gov5e80yf0omHYlEBbgTe0QRhEHeWilhiS8_DnO2dHTrCcr_9LH9MKL0oOj85TJolgA9iF1Kq6ZOIIJctEn600lHxA9T9bMklO6ox-xiJuBu8eircnHJNrTAAAHAfwHwAdme4xio7yUVXSzJadRPewAfTkIUFqlzk7utOyeRTzgB9iBDISt1EFYdta5UGhlAueDIH_8ykA9g5TQ