### BROWSE
GET http://localhost:8080/api/user/browse
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MjAxMDg4NDQsImV4cCI6MTcyMDExMjQ0NCwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluQG9wbGF5LmZyIn0.jBYWDUUBJvRmeaLLRkmNMjiXhDLY5vKoHMqESskJnn4Y-rk-yp4Nb_IGB2gmK57UihP_51exn3l_pwQcLGDIBZR0yf7wgG4h-FoEmlEj2cX-r4D9S0l3Y19D5Kas_DXGuGtZJFozIAQLMbeH6HKNzxlrB-iMEgw5UIK74L9F95Kr_SBYhU4G0xyIVRhj_8Vuw5p-6WZb6rOqf0_UCh38L4XHOMiMG6vHi2OjUYbOi61esboPTrR7InG9qxrRA9-JkMlJPqStzkiRqxviJNBR-GKq1DKG_XGU0HdF_BxpZhw9xIY73n3XMS9CzU3Yqz5nymmHaYRQ7STaYKujiyIyvg

### SHOW{id}
GET http://localhost:8080/api/user/2/show
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MjAxMDg4NDQsImV4cCI6MTcyMDExMjQ0NCwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluQG9wbGF5LmZyIn0.jBYWDUUBJvRmeaLLRkmNMjiXhDLY5vKoHMqESskJnn4Y-rk-yp4Nb_IGB2gmK57UihP_51exn3l_pwQcLGDIBZR0yf7wgG4h-FoEmlEj2cX-r4D9S0l3Y19D5Kas_DXGuGtZJFozIAQLMbeH6HKNzxlrB-iMEgw5UIK74L9F95Kr_SBYhU4G0xyIVRhj_8Vuw5p-6WZb6rOqf0_UCh38L4XHOMiMG6vHi2OjUYbOi61esboPTrR7InG9qxrRA9-JkMlJPqStzkiRqxviJNBR-GKq1DKG_XGU0HdF_BxpZhw9xIY73n3XMS9CzU3Yqz5nymmHaYRQ7STaYKujiyIyvg

### Register User
POST http://localhost:8080/api/user/register
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MjAxMDUyMzMsImV4cCI6MTcyMDEwODgzMywicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluQG9wbGF5LmZyIn0.ge5YrrBESVpNxPiy8GU7o4BRQQmPvxhtP2IcghYyFE1B7eS7e_kGNUjE4fnncadd31ZOAp1-6ip90mCxLX_BZxnEF9hovCIhIgInnQ-1PeFKSYOVT4pyo-YGn2_URQMhDDXgaMPQDafyEDhNWmFMKE7UkaYwWFDTFx9Qow-VEp3Z52RIwF4UPX4bZJZdeBjIuV6vgnK-TbHqamF6pLGLLhlbZeMFGduFFozLC_tqD1b7uh1NfAi3Ai1hn2zN-mc2g2cb0BWmml_clPaaNJEueprnWaqM6pFHD7pUTZ_qQA4b_i5IBdFz6a4TEQSJ4_xCJrTAm0a0J-KIJLuwSYbjmw

{
    "firstname": "John",
    "lastname": "Doe",
    "nickname": "johndoe",
    "email": "john.doe@example.com",
    "password": "password123",
    "picture": ""
}
