### Add to CART
POST http://localhost:8080/api/order/add
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MjA4NjY4ODcsImV4cCI6MTcyMDg3MDQ4Nywicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluQG9wbGF5LmZyIn0.oQk0doisV5ZWTqU6zkA_CMJKR8gnPvrelbpDPFesVhUoJwVZjVA_APEU-ljE1QI372YN4JjLj9QoDmzRYHvDVQz8sjeoSVjaUZsu_fNlWXnH8Zc-j4oL0stFNFze6K7GeVPMpw17qQs25UjY0lEBq4E_uwLZVi0WkkEx3y-eZKgB6VWJ9F8tmrJEd1PxQzx6RqB3xP0BcmaJ1HbYKshb7bEFVUCck04F4gRC6HCfg-sEzzBg8WPUcc5w9Xh4dplAxSHaOYKj_MH6WnRjQQUjzrOXW7H6tOEcWMpj194pPnbS1f29N235E-qdfBZYRlyUmbG4VcXqERJygxe7_ahu_Q

{
    "game_id": 220
}


### Remove from CART
POST http://localhost:8080/api/order/remove
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MjA4NjY4ODcsImV4cCI6MTcyMDg3MDQ4Nywicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluQG9wbGF5LmZyIn0.oQk0doisV5ZWTqU6zkA_CMJKR8gnPvrelbpDPFesVhUoJwVZjVA_APEU-ljE1QI372YN4JjLj9QoDmzRYHvDVQz8sjeoSVjaUZsu_fNlWXnH8Zc-j4oL0stFNFze6K7GeVPMpw17qQs25UjY0lEBq4E_uwLZVi0WkkEx3y-eZKgB6VWJ9F8tmrJEd1PxQzx6RqB3xP0BcmaJ1HbYKshb7bEFVUCck04F4gRC6HCfg-sEzzBg8WPUcc5w9Xh4dplAxSHaOYKj_MH6WnRjQQUjzrOXW7H6tOEcWMpj194pPnbS1f29N235E-qdfBZYRlyUmbG4VcXqERJygxe7_ahu_Q

{
    "game_id": 234,
    "quantity": 1
}

### Remove CART
POST http://localhost:8080/api/order/clear
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MjA4NjY4ODcsImV4cCI6MTcyMDg3MDQ4Nywicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluQG9wbGF5LmZyIn0.oQk0doisV5ZWTqU6zkA_CMJKR8gnPvrelbpDPFesVhUoJwVZjVA_APEU-ljE1QI372YN4JjLj9QoDmzRYHvDVQz8sjeoSVjaUZsu_fNlWXnH8Zc-j4oL0stFNFze6K7GeVPMpw17qQs25UjY0lEBq4E_uwLZVi0WkkEx3y-eZKgB6VWJ9F8tmrJEd1PxQzx6RqB3xP0BcmaJ1HbYKshb7bEFVUCck04F4gRC6HCfg-sEzzBg8WPUcc5w9Xh4dplAxSHaOYKj_MH6WnRjQQUjzrOXW7H6tOEcWMpj194pPnbS1f29N235E-qdfBZYRlyUmbG4VcXqERJygxe7_ahu_Q

### Checkout
POST http://localhost:8080/api/order/checkout
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MjA4NjY4ODcsImV4cCI6MTcyMDg3MDQ4Nywicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluQG9wbGF5LmZyIn0.oQk0doisV5ZWTqU6zkA_CMJKR8gnPvrelbpDPFesVhUoJwVZjVA_APEU-ljE1QI372YN4JjLj9QoDmzRYHvDVQz8sjeoSVjaUZsu_fNlWXnH8Zc-j4oL0stFNFze6K7GeVPMpw17qQs25UjY0lEBq4E_uwLZVi0WkkEx3y-eZKgB6VWJ9F8tmrJEd1PxQzx6RqB3xP0BcmaJ1HbYKshb7bEFVUCck04F4gRC6HCfg-sEzzBg8WPUcc5w9Xh4dplAxSHaOYKj_MH6WnRjQQUjzrOXW7H6tOEcWMpj194pPnbS1f29N235E-qdfBZYRlyUmbG4VcXqERJygxe7_ahu_Q